export const USER_SIGNIN_REQUEST = "USER_SIGIN_REQUEST";
export const USER_SIGNIN_SUCESS = "USER_SIGIN_SUCESS";
export const USER_SIGNIN_FAIL = "USER_SIGIN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const CREATE_NOTE = "CREATE_NOTE";